### ISSUE TITLE
Disable shortcut not working

### ISSUE THREAD

**Issue by fritzophrenic** [Lord-Kamina/keybinder#12] opened 2016-07-15 15:50 UTC
I tried disabling the "Control + W" keyboard shortcut to close a tab, because I keep accidentally using it after typing a large amount of text, losing it all.

It shows as disabled and stricken out in the settings. However, CTRL+W still closes the tab.

To actually disable CTRL+W, I had to assign a different shortcut key. Now CTRL+W does not close the tab, only the new shortcut.

Please fix the "disable" feature so I don't need to assign some other shortcut for a feature I don't plan to use.

Version 1.3.0, updated June 13, 2016.

**Comment by Lord-Kamina** [comment] 2016-07-15 16:00
I will check this out as soon as I can.

Can you replicate this behavior for other shortcuts?

**Comment by fritzophrenic** [comment] 2016-07-15 16:22
I tried it with CTRL+T (opening a new tab). Disabling that one seems to work properly without assigning a different shortcut.

**Comment by Lord-Kamina** [comment] 2016-07-15 16:25
Anyway, I'll look into it and try to find what's different between those
two shortcuts such that one would work and another wouldn't.

Thanks for the report!

**Comment by fritzophrenic** [comment] 2016-07-15 16:25
I think in a prior version disabling CTRL+W also worked, by the way. I remember setting it up and trying it out and seeing it work some months ago, but when I accidentally hit CTRL+W today the tab closed. I went to go check the configuration and saw it was still disabled in the options. I tried re-enabling it and disabling it again and the close tab function was still bound to CTRL+W anyway. So I assigned it to CTRL+Q and now the function is re-bound to CTRL+Q and CTRL+W does nothing as expected. I don't know if other shortcuts are affected, but as mentioned CTRL+T does not seem to be affected.

**Comment by Lord-Kamina** [comment] 2016-07-15 16:33
I recently did some re-factoring of the code dealing with modifying more
than one window and other things in that respect, perhaps I broke something
along the way.

**Comment by wblock** [comment] 2016-10-14 15:40
Disabled shortcuts only work immediately after they have been disabled.  For instance, even after Ctrl-W has been disabled previously, it still closes a tab.  But go to a tab, bring up the dialog, enable and then disable Ctrl-W, and then it is disabled.  But only in that tab.

**Comment by Lord-Kamina** [comment] 2016-10-14 16:20
I haven't really experienced this but I believe it is related to another
error reported a couple days ago. That is already fixed and will be coming
out in the next release in a couple of days. Please wait until then to see
if the problem is solved.

**Comment by Lord-Kamina** [comment] 2016-11-23 20:32
This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Closed** 2016-12-22 01:06 UTC
Labels: bug
