### ISSUE TITLE
Shortcuts only work in first opened window

### ISSUE THREAD

**Issue by advancingu** [Lord-Kamina/keybinder#16] opened 2016-09-05 08:59 UTC
Steps to reproduce:
- Have two Firefox windows open with a bunch of tabs.
- Assert that Firefox is configured to reopen previous tabs and windows when launching.
- Close Firefox.
- Start Firefox.
- Check which window comes up first.

Actual behavior:
- Shortcuts only work in the window that comes up first.

Expected behavior:
- Shortcuts work in all opened windows.
- Tab access by numbers works within the tabs of each window.

**Comment by Lord-Kamina** [comment] 2016-09-05 10:51
I'll see if I can reproduce this; although I'm not sure I'll be able to. I used to have this problem (which is sort-of derived of moving away from a deprecated API in favor of a more-roundabout but current way of handling windows) but haven't experienced such an issue in a while. To be fair, though, I use the Session Manager add-on.

Could you perhaps provide a log to see whether I can spot any actual errors?

**Comment by advancingu** [comment] 2016-09-05 10:53
Where would I find those logs?

**Comment by Lord-Kamina** [comment] 2016-09-05 10:57
Browser console or by launching firefox from the command-line and copying the output. Also; I just tried doing what you described and cannot reproduce the issue. Maybe there's something different in the way Session Manager handles window opening?

**Comment by Lord-Kamina** [comment] 2016-11-23 20:30
This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Closed by Lord-Kamina** 2016-11-23 20:30 UTC
Labels: bug

**Comment by advancingu** [comment] 2016-11-23 20:33
Thanks for implementing a fix! Will check again once I have this version.
