### ISSUE TITLE
Focus Stealing From Plugins Refuses To Fully Disable

### ISSUE THREAD

**Issue by ShylokVakarian** [Lord-Kamina/keybinder#18] opened 2016-10-24 15:21 UTC
Using latest version of Firefox as of October 24th at 10:18 AM.  Focus is being stolen from plugins that require the keyboard to function.  Unchecked Steal Focus From Plugins, but still stealing focus.  Attempted to edit Address Patterns to get the plugin to stop stealing focus from plugins, but the Ok button refuses to work regardless of what the contents of the list are, including the default list of "*".

**Comment by Lord-Kamina** [comment] 2016-10-25 18:18
I had replied to your review, but considering this, fair enough. I'm about
to release a new version that (should) correct most of these issues. Would
you mind checking the console and pasting some of the errors, so I can make
sure they are indeed solved before the release?

**Comment by ShylokVakarian** [comment] 2016-10-26 14:21
How would I do that?  What console do I use?

**Comment by Lord-Kamina** [comment] 2016-10-27 15:43
Open the browser console and make sure it's only showing javascript, then
search for keybinder.

If nothing is shown, try reproducing the behaviors you know don't work. And
if you still see nothing, try doing the same using the Firefox developer
edition.

**Comment by ShylokVakarian** [comment] 2016-10-28 01:54
I had edited the previous message.  Please view on GitHub to see the edited
message.

**Comment by Lord-Kamina** [comment] 2016-10-29 10:57
I just saw. Thank you.


That error at least is for certain fixed in the upcoming version, that was
actually a regression caused by some refactoring I had done.

If you find any other errors, feel free to post them here so I can take a
look.

**Comment by Lord-Kamina** [comment] 2016-11-23 20:30
This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Closed** 2016-12-22 01:07 UTC
